use super::scenario::{reinforcement, side, standard_turn_sequence};
use super::{HexId, ReinforcementDefinition, ScenarioDefinition, UnitLocation};

fn hex(id: &str) -> UnitLocation {
    UnitLocation::Hex {
        hex_id: HexId(id.to_owned()),
    }
}

fn reserve() -> UnitLocation {
    UnitLocation::StrategicReserve
}

#[allow(clippy::too_many_arguments)]
fn unit(
    game_turn: u16,
    id: &str,
    name: &str,
    side_id: &str,
    nation_id: &str,
    unit_type_id: &str,
    formation_id: Option<&str>,
    location: UnitLocation,
    traits: &[&str],
    steps: &[(u16, u16, u16)],
) -> ReinforcementDefinition {
    reinforcement(
        game_turn,
        id,
        name,
        side_id,
        nation_id,
        unit_type_id,
        formation_id,
        location,
        traits,
        steps,
    )
}

pub(crate) fn baltap_scenario() -> ScenarioDefinition {
    ScenarioDefinition {
        id: "nato-baltap-1983".to_owned(),
        name: "BALTAP 1983 Introductory Scenario".to_owned(),
        max_game_turns: 7,
        sides: vec![side("warsawPact", "Warsaw Pact"), side("nato", "NATO")],
        turn_sequence: standard_turn_sequence(),
        reinforcements: baltap_units(),
    }
}

fn baltap_units() -> Vec<ReinforcementDefinition> {
    vec![
        unit(
            1,
            "westGermany.landjut.hq",
            "West German LANDJUT Corps HQ",
            "nato",
            "westGermany",
            "headquarters",
            Some("nato.landjut"),
            hex("2117"),
            &["headquarters"],
            &[(3, 1, 4)],
        ),
        unit(
            1,
            "denmark.jutland.2mechanizedBrigade",
            "Danish 2nd Mechanized Brigade, Jutland Division",
            "nato",
            "denmark",
            "mechanizedBrigade",
            Some("denmark.jutlandDivision"),
            hex("0819"),
            &[],
            &[(2, 2, 5)],
        ),
        unit(
            1,
            "denmark.jutland.1mechanizedBrigade",
            "Danish 1st Mechanized Brigade, Jutland Division",
            "nato",
            "denmark",
            "mechanizedBrigade",
            Some("denmark.jutlandDivision"),
            hex("1417"),
            &[],
            &[(2, 2, 5)],
        ),
        unit(
            1,
            "denmark.landzealand.hq",
            "Danish LANDZEALAND Corps HQ",
            "nato",
            "denmark",
            "headquarters",
            Some("nato.landzealand"),
            hex("1411"),
            &["headquarters"],
            &[(3, 1, 4)],
        ),
        unit(
            1,
            "soviet.2gta.21motorRifleDivision",
            "Soviet 21st Motor Rifle Division",
            "warsawPact",
            "sovietUnion",
            "motorRifleDivision",
            Some("soviet.2ndGuardsTankArmy"),
            hex("2412"),
            &[],
            &[(8, 6, 5), (4, 4, 5)],
        ),
        unit(
            1,
            "denmark.landzealand.1mechanizedBrigade",
            "Danish 1st Mechanized Brigade, Zealand",
            "nato",
            "denmark",
            "mechanizedBrigade",
            Some("denmark.landzealand"),
            hex("1411"),
            &[],
            &[(2, 2, 5)],
        ),
        unit(
            1,
            "denmark.landzealand.2mechanizedBrigade",
            "Danish 2nd Mechanized Brigade, Zealand",
            "nato",
            "denmark",
            "mechanizedBrigade",
            Some("denmark.landzealand"),
            hex("1611"),
            &[],
            &[(2, 2, 5)],
        ),
        unit(
            1,
            "soviet.2gta.16guardsTankDivision",
            "Soviet 16th Guards Tank Division",
            "warsawPact",
            "sovietUnion",
            "tankDivision",
            Some("soviet.2ndGuardsTankArmy"),
            hex("2412"),
            &[],
            &[(10, 6, 6), (5, 4, 6)],
        ),
        unit(
            3,
            "westGermany.6panzergrenadierDivision.51homeDefenseBrigade",
            "West German 51st Home Defense Brigade",
            "nato",
            "westGermany",
            "homeDefenseBrigade",
            Some("westGermany.6thPanzergrenadierDivision"),
            reserve(),
            &["territorial"],
            &[(3, 2, 5)],
        ),
        unit(
            3,
            "unitedKingdom.landjut.1brigade",
            "British 1st Brigade",
            "nato",
            "unitedKingdom",
            "infantryBrigade",
            Some("nato.landjut"),
            reserve(),
            &[],
            &[(2, 2, 5)],
        ),
        unit(
            2,
            "soviet.balticFront.hq",
            "Soviet Baltic Front HQ",
            "warsawPact",
            "sovietUnion",
            "headquarters",
            Some("soviet.balticFront"),
            reserve(),
            &["headquarters"],
            &[(6, 1, 4)],
        ),
        unit(
            4,
            "unitedStates.9infantryDivision.3brigade",
            "U.S. 3rd Brigade, 9th Infantry Division",
            "nato",
            "unitedStates",
            "airmobileInfantryBrigade",
            Some("unitedStates.9thInfantryDivision"),
            reserve(),
            &["airmobile"],
            &[(2, 1, 6)],
        ),
        unit(
            4,
            "westGermany.61homeDefenseBrigade",
            "West German 61st Home Defense Brigade",
            "nato",
            "westGermany",
            "homeDefenseBrigade",
            None,
            reserve(),
            &["territorial"],
            &[(1, 1, 5)],
        ),
        unit(
            5,
            "unitedStates.9infantryDivision.1brigade",
            "U.S. 1st Brigade, 9th Infantry Division",
            "nato",
            "unitedStates",
            "airmobileInfantryBrigade",
            Some("unitedStates.9thInfantryDivision"),
            reserve(),
            &["airmobile"],
            &[(2, 1, 6)],
        ),
        unit(
            6,
            "unitedStates.9infantryDivision.2brigade",
            "U.S. 2nd Brigade, 9th Infantry Division",
            "nato",
            "unitedStates",
            "airmobileInfantryBrigade",
            Some("unitedStates.9thInfantryDivision"),
            reserve(),
            &["airmobile"],
            &[(2, 1, 6)],
        ),
        unit(
            1,
            "soviet.7guardsAirborneDivision.119regiment",
            "Soviet 119th Guards Airborne Regiment",
            "warsawPact",
            "sovietUnion",
            "airborneRegiment",
            Some("soviet.7thGuardsAirborneDivision"),
            reserve(),
            &["airborne"],
            &[(2, 2, 4)],
        ),
        unit(
            2,
            "denmark.4zealandBrigade",
            "Danish 4th Zealand Brigade",
            "nato",
            "denmark",
            "territorialBrigade",
            None,
            reserve(),
            &["territorial"],
            &[(1, 1, 4)],
        ),
        unit(
            2,
            "unitedKingdom.5parachuteBrigade",
            "British 5th Parachute Brigade",
            "nato",
            "unitedKingdom",
            "airborneBrigade",
            None,
            reserve(),
            &["airborne"],
            &[(1, 1, 5)],
        ),
        unit(
            2,
            "denmark.2zealandBrigade",
            "Danish 2nd Zealand Brigade",
            "nato",
            "denmark",
            "territorialBrigade",
            None,
            reserve(),
            &["territorial"],
            &[(0, 1, 4)],
        ),
        unit(
            2,
            "denmark.3zealandBrigade",
            "Danish 3rd Zealand Brigade",
            "nato",
            "denmark",
            "territorialBrigade",
            None,
            reserve(),
            &["territorial"],
            &[(0, 1, 4)],
        ),
        unit(
            2,
            "denmark.militaryRegion4",
            "Danish Military Region IV",
            "nato",
            "denmark",
            "territorialBrigade",
            None,
            reserve(),
            &["territorial"],
            &[(0, 1, 4)],
        ),
        unit(
            2,
            "denmark.1zealandBrigade",
            "Danish 1st Zealand Brigade",
            "nato",
            "denmark",
            "territorialBrigade",
            None,
            reserve(),
            &["territorial"],
            &[(0, 1, 4)],
        ),
        unit(
            2,
            "denmark.militaryRegion2",
            "Danish Military Region II",
            "nato",
            "denmark",
            "territorialBrigade",
            None,
            reserve(),
            &["territorial"],
            &[(0, 1, 4)],
        ),
        unit(
            2,
            "denmark.militaryRegion3",
            "Danish Military Region III",
            "nato",
            "denmark",
            "territorialBrigade",
            None,
            reserve(),
            &["territorial"],
            &[(0, 1, 4)],
        ),
        unit(
            2,
            "denmark.jutlandBattleGroup",
            "Danish Jutland Battle Group",
            "nato",
            "denmark",
            "territorialBrigade",
            None,
            reserve(),
            &["territorial"],
            &[(1, 2, 4)],
        ),
        unit(
            2,
            "denmark.militaryRegion1",
            "Danish Military Region I",
            "nato",
            "denmark",
            "territorialBrigade",
            None,
            reserve(),
            &["territorial"],
            &[(0, 1, 4)],
        ),
        unit(
            1,
            "soviet.2gta.94guardsMotorRifleDivision",
            "Soviet 94th Guards Motor Rifle Division",
            "warsawPact",
            "sovietUnion",
            "motorRifleDivision",
            Some("soviet.2ndGuardsTankArmy"),
            hex("2412"),
            &[],
            &[(8, 6, 5), (4, 4, 5)],
        ),
        unit(
            1,
            "eastGermany.2gta.8motorRifleDivision",
            "East German 8th Motor Rifle Division",
            "warsawPact",
            "eastGermany",
            "motorRifleDivision",
            Some("soviet.2ndGuardsTankArmy"),
            hex("2412"),
            &[],
            &[(6, 5, 5), (3, 3, 5)],
        ),
        unit(
            1,
            "soviet.balticFront.37airborneBrigade",
            "Soviet 37th Airborne Brigade",
            "warsawPact",
            "sovietUnion",
            "airborneBrigade",
            Some("soviet.balticFront"),
            reserve(),
            &["airborne"],
            &[(1, 1, 5)],
        ),
        unit(
            1,
            "soviet.northernEastGermanyFront.hq",
            "Soviet Northern East Germany Front HQ",
            "warsawPact",
            "sovietUnion",
            "headquarters",
            Some("soviet.northernEastGermanyFront"),
            hex("2613"),
            &["headquarters"],
            &[(6, 1, 4)],
        ),
        unit(
            1,
            "westGermany.6panzergrenadierDivision.18panzerBrigade",
            "West German 18th Panzer Brigade",
            "nato",
            "westGermany",
            "armoredBrigade",
            Some("westGermany.6thPanzergrenadierDivision"),
            hex("2216"),
            &[],
            &[(5, 3, 6)],
        ),
        unit(
            1,
            "westGermany.6panzergrenadierDivision.16panzergrenadierBrigade",
            "West German 16th Panzergrenadier Brigade",
            "nato",
            "westGermany",
            "mechanizedBrigade",
            Some("westGermany.6thPanzergrenadierDivision"),
            hex("2415"),
            &[],
            &[(3, 3, 6)],
        ),
        unit(
            1,
            "westGermany.6panzergrenadierDivision.17panzergrenadierBrigade",
            "West German 17th Panzergrenadier Brigade",
            "nato",
            "westGermany",
            "mechanizedBrigade",
            Some("westGermany.6thPanzergrenadierDivision"),
            hex("2415"),
            &[],
            &[(3, 3, 6)],
        ),
        unit(
            1,
            "denmark.jutland.3mechanizedBrigade",
            "Danish 3rd Mechanized Brigade, Jutland Division",
            "nato",
            "denmark",
            "mechanizedBrigade",
            Some("denmark.jutlandDivision"),
            hex("1618"),
            &[],
            &[(2, 2, 5)],
        ),
        unit(
            1,
            "soviet.northernEastGermanyFront.221tankRegiment",
            "Soviet 221st Tank Regiment",
            "warsawPact",
            "sovietUnion",
            "tankRegiment",
            Some("soviet.northernEastGermanyFront"),
            hex("2412"),
            &[],
            &[(2, 2, 6)],
        ),
        unit(
            1,
            "soviet.balticCorps.138tankRegiment",
            "Soviet 138th Tank Regiment",
            "warsawPact",
            "sovietUnion",
            "tankRegiment",
            Some("soviet.balticCorps"),
            hex("2412"),
            &[],
            &[(2, 2, 6)],
        ),
        unit(
            1,
            "soviet.7guardsAirborneDivision.97regiment",
            "Soviet 97th Guards Airborne Regiment",
            "warsawPact",
            "sovietUnion",
            "airborneRegiment",
            Some("soviet.7thGuardsAirborneDivision"),
            reserve(),
            &["airborne"],
            &[(2, 2, 4)],
        ),
        unit(
            1,
            "soviet.7guardsAirborneDivision.108regiment",
            "Soviet 108th Guards Airborne Regiment",
            "warsawPact",
            "sovietUnion",
            "airborneRegiment",
            Some("soviet.7thGuardsAirborneDivision"),
            reserve(),
            &["airborne"],
            &[(2, 2, 4)],
        ),
        unit(
            1,
            "soviet.76guardsAirborneDivision.237regiment",
            "Soviet 237th Guards Airborne Regiment",
            "warsawPact",
            "sovietUnion",
            "airborneRegiment",
            Some("soviet.76thGuardsAirborneDivision"),
            reserve(),
            &["airborne"],
            &[(2, 2, 4)],
        ),
        unit(
            1,
            "soviet.76guardsAirborneDivision.104regiment",
            "Soviet 104th Guards Airborne Regiment",
            "warsawPact",
            "sovietUnion",
            "airborneRegiment",
            Some("soviet.76thGuardsAirborneDivision"),
            reserve(),
            &["airborne"],
            &[(2, 2, 4)],
        ),
        unit(
            1,
            "soviet.76guardsAirborneDivision.234regiment",
            "Soviet 234th Guards Airborne Regiment",
            "warsawPact",
            "sovietUnion",
            "airborneRegiment",
            Some("soviet.76thGuardsAirborneDivision"),
            reserve(),
            &["airborne"],
            &[(2, 2, 4)],
        ),
        unit(
            1,
            "poland.balticCorps.7marineBrigade",
            "Polish 7th Marine Brigade",
            "warsawPact",
            "poland",
            "marineBrigade",
            Some("soviet.balticCorps"),
            reserve(),
            &["marine"],
            &[(3, 3, 4)],
        ),
        unit(
            1,
            "soviet.balticCorps.hq",
            "Soviet Baltic Corps HQ",
            "warsawPact",
            "sovietUnion",
            "headquarters",
            Some("soviet.balticCorps"),
            reserve(),
            &["headquarters", "marine"],
            &[(2, 1, 1)],
        ),
        unit(
            1,
            "soviet.balticCorps.336guardsMarineBrigade",
            "Soviet 336th Guards Marine Brigade",
            "warsawPact",
            "sovietUnion",
            "marineBrigade",
            Some("soviet.balticCorps"),
            reserve(),
            &["marine"],
            &[(3, 3, 4)],
        ),
    ]
}
